export const ADMIN_TRADES_FETCH_REQUEST = "ADMIN_TRADES_FETCH_REQUEST";
export const ADMIN_TRADES_FETCH_SUCCESS = "ADMIN_TRADES_FETCH_SUCCESS";
export const ADMIN_TRADES_FETCH_FAIL = "ADMIN_TRADES_FETCH_FAIL";

export const ADMIN_COUNT_FETCH_REQUEST = "ADMIN_COUNT_FETCH_REQUEST";
export const ADMIN_COUNT_FETCH_SUCCESS = "ADMIN_COUNT_FETCH_SUCCESS";
export const ADMIN_COUNT_FETCH_FAIL = "ADMIN_COUNT_FETCH_FAIL";
