export const CHAT_FETCH_REQUEST = "CHAT_FETCH_REQUEST"
export const CHAT_FETCH_SUCCESS = "CHAT_FETCH_SUCCESS"
export const CHAT_FETCH_FAIL = "CHAT_FETCH_FAIL"
export const CHAT_FETCH_RESET = "CHAT_FETCH_RESET"