export const TRADE_CREATE_REQUEST = "TRADE_CREATE_REQUEST";
export const TRADE_CREATE_SUCCESS = "TRADE_CREATE_SUCCESS";
export const TRADE_CREATE_FAIL = "TRADE_CREATE_FAIL";

export const TRADE_FETCH_REQUEST = "TRADE_FETCH_REQUEST";
export const TRADE_FETCH_SUCCESS = "TRADE_FETCH_SUCCESS";
export const TRADE_FETCH_FAIL = "TRADE_FETCH_FAIL";

export const TNX_CREATE_REQUEST = "TNX_CREATE_REQUEST";
export const TNX_CREATE_SUCCESS = "TNX_CREATE_SUCCESS";
export const TNX_CREATE_FAIL = "TNX_CREATE_FAIL";

export const BALANCE_FETCH_REQUEST = "BALANCE_FETCH_REQUEST";
export const BALANCE_FETCH_SUCCESS = "BALANCE_FETCH_SUCCESS";
export const BALANCE_FETCH_FAIL = "BALANCE_FETCH_FAIL";
export const BALANCE_RESET = "BALANCE_RESET";

export const TRANSFER_REQUEST = "TRANSFER_REQUEST";
export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";
export const TRANSFER_FAIL = "TRANSFER_FAIL";
export const TRANSFER_RESET = "TRANSFER_RESET";

export const SINGLE_TRADE_REQUEST = "SINGLE_TRADE_REQUEST";
export const SINGLE_TRADE_SUCCESS = "SINGLE_TRADE_SUCCESS";
export const SINGLE_TRADE_FAIL = "SINGLE_TRADE_FAIL";
export const SINGLE_TRADE_RESET = "SINGLE_TRADE_RESET";

export const CHANGE_TRADE_REQUEST = "CHANGE_TRADE_REQUEST";
export const CHANGE_TRADE_SUCCESS = "CHANGE_TRADE_SUCCESS";
export const CHANGE_TRADE_FAIL = "CHANGE_TRADE_FAIL";
export const CHANGE_TRADE_RESET = "CHANGE_TRADE_RESET";
